// This file is auto-generated by server.py on startup
// Do not edit manually. Last updated: 2025-12-28 22:06:48

window.GENERATED_BID_DATA = [
    {
        "title": "＜契約情報の公開＞",
        "category": "agriculture",
        "agency": "独立行政法人国立病院機構東徳島医療センター",
        "date": "2025年12月26日",
        "url": "https://www.kkj.go.jp/d/?D=dG9rdXNoaW1hL2hpZ2FzaGl0b2t1c2hpbWFfaXJ5b19jZW50ZXIvMjAyNS8yMDI1MTIyNl8wMDMyNwo=&L=ja"
    },
    {
        "title": "長崎県教育委員会所管施設で使用する電力調達に係る一般競争入札",
        "category": "agriculture",
        "agency": "長崎県",
        "date": "2025年12月26日",
        "url": "https://www.kkj.go.jp/d/?D=bmFnYXNha2kvbmFnYXNha2lrZW4vMjAyNS8yMDI1MTIyNl8wNDk5Ngo=&L=ja"
    },
    {
        "title": "村道2076号線側溝改修工事",
        "category": "agriculture",
        "agency": "長野県南箕輪村",
        "date": "2025年12月26日",
        "url": "https://www.kkj.go.jp/d/?D=bmFnYW5vL21pbmFtaW1pbm93YV92aWxsLzIwMjUvMjAyNTEyMjZfMDA3NjYK&L=ja"
    },
    {
        "title": "令和8年1月14日 一般競争入札予定【電子メール入札】(委託：韮崎市立小学校給食調理業務委託）",
        "category": "food",
        "agency": "山梨県韮崎市",
        "date": "2025年12月26日",
        "url": "https://www.kkj.go.jp/d/?D=eWFtYW5hc2hpL25pcmFzYWtpX2NpdHkvMjAyNS8yMDI1MTIyNl8wMDE0Mwo=&L=ja"
    },
    {
        "title": "令和8年度流通木材の合法性確認システムに係る運用・保守及びクラウドサービス提供業務(PDF : 241KB)",
        "category": "food",
        "agency": "林野庁",
        "date": "2025年12月26日",
        "url": "https://www.kkj.go.jp/d/?D=dG9reW8vcmlueWFfbWFmZl9nby8yMDI1LzIwMjUxMjI2XzAwMDE4Cg==&L=ja"
    },
    {
        "title": "令和8年度国有林野地理情報高度化システム運用・保守業務(PDF : 168KB)",
        "category": "food",
        "agency": "林野庁",
        "date": "2025年12月26日",
        "url": "https://www.kkj.go.jp/d/?D=dG9reW8vcmlueWFfbWFmZl9nby8yMDI1LzIwMjUxMjI2XzAwMDE3Cg==&L=ja"
    },
    {
        "title": "令和8年度版「森林へようこそ」の印刷製造・発送支援業務(PDF : 181KB)",
        "category": "food",
        "agency": "林野庁",
        "date": "2025年12月26日",
        "url": "https://www.kkj.go.jp/d/?D=dG9reW8vcmlueWFfbWFmZl9nby8yMDI1LzIwMjUxMjI2XzAwMDE2Cg==&L=ja"
    },
    {
        "title": "院内清掃業務委託一式",
        "category": "food",
        "agency": "独立行政法人国立病院機構米沢病院",
        "date": "2025年12月26日",
        "url": "https://www.kkj.go.jp/d/?D=eWFtYWdhdGEveW9uZXphd2FfaG9zcC8yMDI1LzIwMjUxMjI2XzAwMjc5Cg==&L=ja"
    },
    {
        "title": "病院物流管理業務",
        "category": "food",
        "agency": "国立大学法人鳥取大学",
        "date": "2025年12月26日",
        "url": "https://www.kkj.go.jp/d/?D=dG90dG9yaS90b3R0b3JpX3VfYWMvMjAyNS8yMDI1MTIyNl8wMDAyOAo=&L=ja"
    },
    {
        "title": "医療材料等物品管理業務委託 一式",
        "category": "food",
        "agency": "独立行政法人国立病院機構米子医療センター",
        "date": "2025年12月26日",
        "url": "https://www.kkj.go.jp/d/?D=dG90dG9yaS95b25hZ29faXJ5b19jZW50ZXIvMjAyNS8yMDI1MTIyNl8wMDAxNAo=&L=ja"
    },
    {
        "title": "患者給食に関する配膳・下膳及び食器・調理器具の洗浄並びに清掃等業務",
        "category": "food",
        "agency": "国立大学法人筑波大学",
        "date": "2025年12月26日",
        "url": "https://www.kkj.go.jp/d/?D=aWJhcmFraS90c3VrdWJhX2FjLzIwMjUvMjAyNTEyMjZfMDEwODkK&L=ja"
    },
    {
        "title": "令和8年度我孫子市学校給食調理業務委託",
        "category": "food",
        "agency": "千葉県我孫子市",
        "date": "2025年12月25日",
        "url": "https://www.kkj.go.jp/d/?D=Y2hpYmEvYWJpa29fY2l0eS8yMDI1LzIwMjUxMjI1XzAwMTExCg==&L=ja"
    },
    {
        "title": "Ｒ８江戸川管内通信設備保守・運転監視業務 [PDF：201KB]",
        "category": "food",
        "agency": "国土交通省関東地方整備局江戸川河川事務所",
        "date": "2025年12月24日",
        "url": "https://www.kkj.go.jp/d/?D=Z292My9rdHJfbWxpdC8yMDI1LzIwMjUxMjI0XzA0ODgzCg==&L=ja"
    },
    {
        "title": "東海農政局庁舎移転に伴う物品移設等業務(PDF : 197KB)",
        "category": "farmstay",
        "agency": "農林水産省東海農政局",
        "date": "2025年11月4日",
        "url": "https://www.kkj.go.jp/d/?D=Z292Mi9tYWZmX3Rva2FpLzIwMjUvMjAyNTExMDRfMDAyNjUK&L=ja"
    },
    {
        "title": "梱包及び発送業務（単価）",
        "category": "other",
        "agency": "農林水産省",
        "date": "2025年12月26日",
        "url": "https://www.kkj.go.jp/d/?D=c2VhcmNoL3BfcG9ydGFsLzIwMjUvMTIvMjAyNTEyMjZfNTYwNDAK&L=ja"
    },
    {
        "title": "農林水産研修所の庁舎等機械警備請負業務",
        "category": "other",
        "agency": "農林水産省",
        "date": "2025年12月26日",
        "url": "https://www.kkj.go.jp/d/?D=c2VhcmNoL3BfcG9ydGFsLzIwMjUvMTIvMjAyNTEyMjZfNTYxMTkK&L=ja"
    },
    {
        "title": "高取山風景林修景伐採事業",
        "category": "other",
        "agency": "農林水産省",
        "date": "2025年12月26日",
        "url": "https://www.kkj.go.jp/d/?D=c2VhcmNoL3BfcG9ydGFsLzIwMjUvMTIvMjAyNTEyMjZfNTYxNDYK&L=ja"
    }
];
