from flask import Flask, send_from_directory, jsonify
import fetch_bids
import os

app = Flask(__name__, static_folder='.', static_url_path='')

@app.route('/')
def serve_index():
    return send_from_directory('.', 'index.html')

import subprocess
import json

@app.route('/api/update')
def api_update():
    print("Received update request, running scraper subprocess...")
    try:
        # Run fetch_bids.py as a separate process to ensure clean state
        subprocess.run(["python", "fetch_bids.py"], check=True)
        
        # Read the generated JSON
        if os.path.exists("data.json"):
            with open("data.json", "r", encoding="utf-8") as f:
                items = json.load(f)
            print(f"Scraper finished. Returning {len(items)} items from data.json.")
            return jsonify(items)
        else:
            return jsonify({"error": "Failed to generate data"}), 500
            
    except Exception as e:
        print(f"Error running scraper: {e}")
        return jsonify({"error": str(e)}), 500

@app.route('/<path:path>')
def serve_static(path):
    return send_from_directory('.', path)

if __name__ == "__main__":
    print("Pre-fetching latest bids... please wait...")
    # Run fetch once at startup to update data.js
    items = fetch_bids.get_latest_bids()
    # Save to data.js explicitly here to ensure index.html picks it up locally if served static, 
    # but more importantly so that when browser loads data.js it is fresh.
    # fetch_bids.get_latest_bids() returns list, we need to save it.
    # Actually fetch_bids main block does the saving, but we imported it.
    # We should add a save function to fetch_bids or just do it here.
    # Let's just rely on the API endpoint or do it here.
    
    # Simple save here
    import json
    from datetime import datetime
    
    js_content = f"""// This file is auto-generated by server.py on startup
// Do not edit manually. Last updated: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}

window.GENERATED_BID_DATA = {json.dumps(items, ensure_ascii=False, indent=4)};
"""
    
    with open("data.js", "w", encoding="utf-8") as f:
        f.write(js_content)
    print("Data refreshed.")

    print("Starting server on http://localhost:5000")
    print("Opening site... (if not, please go to http://localhost:5000)")
    
    # Auto-open browser
    import webbrowser
    webbrowser.open("http://localhost:5000")
    
    app.run(port=5000, debug=False) # debug=True causes reloader to run twice, running scraper twice. False is better.
